name: Build PSP ISO

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pspdev/pspdev:latest
    steps:
      - uses: actions/checkout@v4

      - name: Install mkisofs
        run: |
          apt-get update && apt-get install -y genisoimage

      - name: Fix code header
        run: |
          sed -i '1i #include <stdlib.h>' source/player.c

      - name: Build project and create ISO
        run: |
          make
          mkdir -p iso_root/PSP_GAME/SYSDIR
          mksfo "VoxelCraft" iso_root/PSP_GAME/PARAM.SFO
          cp EBOOT.PBP iso_root/PSP_GAME/SYSDIR/BOOT.BIN
          genisoimage -o game.iso -iso-level 4 iso_root

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: PSP-ISO-File
          path: game.iso
